import { Schema, model } from 'mongoose';

const userSchema = new Schema({
    // _id automatically generated by Mongoose
    firstName: { 
        type: String, 
        required: true 
    },
    lastName: { 
        type: String, 
        required: true 
    },
    email: {
        type: String, 
        required: true, 
        unique: true, 
        lowercase: true 
    },
    passwordHash: { 
        type: String, 
        required: true 
    },
    isEmailVerified: { 
        type: Boolean, 
        default: false 
    },
    verificationTokenHash: {
        type: String
    },
    verificationTokenExpires: {
        type: Date
    },
    passwordResetTokenHash: {
        type: String
    },
    passwordResetTokenExpires: {
        type: Date
    }
}, {
    // Mongoose manages createdAt and updatedAt fields
    timestamps: true
});

export default model('users', userSchema);
